sonar.host.url=http://localhost:9000
sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness and Gym
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.exclusions=.github/**/*,.gitignore,Dockerfile,README.md,requirements.txt
sonar.sourceEncoding=UTF-8
