apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-version-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      version: "a"
  template:
    metadata:
      labels:
        app: aceest
        version: "a"
    spec:
      containers:
      - name: aceest
        image: aceest-fitness:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-version-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      version: "b"
  template:
    metadata:
      labels:
        app: aceest
        version: "b"
    spec:
      containers:
      - name: aceest
        image: aceest-fitness:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-ab-service
spec:
  selector:
    app: aceest
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
