apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      env: production
  template:
    metadata:
      labels:
        app: aceest
        env: production
    spec:
      containers:
      - name: aceest
        image: aceest-fitness:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-shadow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      env: shadow
  template:
    metadata:
      labels:
        app: aceest
        env: shadow
    spec:
      containers:
      - name: aceest
        image: aceest-fitness:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-production-service
spec:
  selector:
    app: aceest
    env: production
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
